#[test]
fn ui_failures() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/ui/node_missing_name.rs");
    t.compile_fail("tests/ui/node_invalid_effect.rs");
    t.compile_fail("tests/ui/node_effect_hint_conflict.rs");
    t.compile_fail("tests/ui/node_determinism_hint_conflict.rs");
    t.compile_fail("tests/ui/node_db_effect_conflict.rs");
    t.compile_fail("tests/ui/node_queue_effect_conflict.rs");
    t.compile_fail("tests/ui/node_blob_determinism_conflict.rs");
    t.compile_fail("tests/ui/workflow_duplicate_alias.rs");
    t.compile_fail("tests/ui/flow_enum_not_enum.rs");
    t.compile_fail("tests/ui/workflow_unknown_alias.rs");
    t.compile_fail("tests/ui/workflow_timeout_missing_edge.rs");
    t.compile_fail("tests/ui/workflow_timeout_invalid_key.rs");
    t.compile_fail("tests/ui/workflow_delivery_missing_edge.rs");
    t.compile_fail("tests/ui/workflow_delivery_invalid_mode.rs");
    t.compile_fail("tests/ui/workflow_delivery_duplicate.rs");
    t.compile_fail("tests/ui/workflow_buffer_missing_edge.rs");
    t.compile_fail("tests/ui/workflow_buffer_invalid_key.rs");
    t.compile_fail("tests/ui/workflow_buffer_duplicate.rs");
    t.compile_fail("tests/ui/workflow_spill_missing_edge.rs");
    t.compile_fail("tests/ui/workflow_spill_invalid_key.rs");
    t.compile_fail("tests/ui/workflow_spill_duplicate.rs");
    t.compile_fail("tests/ui/workflow_delivery_mode_string.rs");
    t.compile_fail("tests/ui/workflow_buffer_max_items_string.rs");
    t.compile_fail("tests/ui/workflow_spill_tier_ident.rs");
    t.compile_fail("tests/ui/workflow_switch_missing_edge.rs");
    t.compile_fail("tests/ui/workflow_switch_duplicate_source.rs");
    t.compile_fail("tests/ui/workflow_switch_invalid_key.rs");
    t.compile_fail("tests/ui/workflow_switch_duplicate_case_key.rs");
}
